#!/usr/bin/ruby
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    xcversion(version: "15.0")
  end

  def build_app
    gym(
      scheme: "LuasWatch WatchKit App",
      destination: "generic/platform=watchOS",
      export_xcargs: "-allowProvisioningUpdates",
      # output_directory: "build/",
      # output_name: "LuasWatchRelease.ipa",
      # archive_path: "build/LuasWatchRelease.xcarchive"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV["TESTFLIGHT_KEY_ID"],
      issuer_id: ENV["TESTFLIGHT_KEY_ISSUER_ID"],
      key_filepath: "fastlane/#{ENV["TESTFLIGHT_KEY_FILENAME"]}"
    )

    clear_derived_data

    increment_build_number

    build_app

    upload_to_testflight(api_key: api_key,
                         skip_waiting_for_build_processing: true)

    commit_version_bump(
        message: 'Build Version Bump by fastlane for TestFlight release',
        force: true
    )
    add_git_tag(tag: "testflight-#{lane_context[SharedValues::BUILD_NUMBER]}")
    push_to_git_remote
  end

  desc "Run unit tests"
  lane :test do
    run_tests(
              devices: ["Apple Watch Series 9 (45mm)"],
              ## destination: "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)",
              scheme: "LuasKitTests",
              testplan: "LuasKitTests",
              buildlog_path: "./fastlane/fastlane-buildlog",
              derived_data_path: "~/Library/Developer/Xcode/DerivedData")
  end

end
