#!/usr/bin/ruby
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do |lane, options|
    xcversion(version: "13.3")
  end

  def build_app
    increment_build_number 
    gym(
      scheme: "LuasWatch WatchKit App",
	destination: "generic/platform=watchOS",
      export_xcargs: "-allowProvisioningUpdates",
      # output_directory: "build/",
      # output_name: "LuasWatchRelease.ipa",
      # archive_path: "build/LuasWatchRelease.xcarchive"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    clear_derived_data
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
    commit_version_bump(
        message: 'Build Version Bump by fastlane for TestFlight release',
        force: true
    )
    add_git_tag(tag: "testflight-#{lane_context[SharedValues::BUILD_NUMBER]}")
    push_to_git_remote
  end

  desc "Run unit tests"
  lane :test do
    run_tests(devices: ["Apple Watch Series 7 - 41mm"],
              scheme: "LuasWatch WatchKit App",
              testplan: "LuasWatch WatchKit App")
    run_tests(devices: ["iPhone 8"],
              scheme: "LuasKitIOSTests")
  end

end
