name: Unit Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: '12.2'
    - name: Run tests
      run: bundle install && bundle exec fastlane test
